# Generated by Django 4.1.3 on 2022-11-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('movies_name', models.CharField(db_column='Movies_name', max_length=100)),
                ('about', models.CharField(blank=True, db_column='About', max_length=150, null=True)),
                ('release_date', models.DateTimeField(blank=True, db_column='Release_date', null=True)),
                ('duration', models.BigIntegerField(db_column='Duration')),
                ('created_on', models.DateTimeField(blank=True, db_column='Created_on', null=True)),
                ('updated_on', models.DateTimeField(blank=True, db_column='Updated_on', null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Movies',
                'managed': False,
            },
        ),
    ]
