# Generated by Django 4.1.3 on 2022-11-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'managed': True, 'verbose_name_plural': 'movies'},
        ),
    ]
