# Generated by Django 4.1.3 on 2022-11-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movies_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movielanguages',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('language', models.CharField(db_column='Language', max_length=20)),
                ('updated_on', models.DateTimeField(blank=True, db_column='Updated_on', null=True)),
                ('created_on', models.DateTimeField(blank=True, db_column='Created_on', null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'MovieLanguages',
                'db_table': 'MovieLanguages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moviedimension',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('dimension', models.CharField(db_column='Dimension', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'MovieDimension',
                'db_table': 'MovieDimension',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Moviegenre',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('genre_name', models.CharField(db_column='Genre_name', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'MovieGenre',
                'db_table': 'MovieGenre',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'managed': True, 'verbose_name_plural': 'Movies'},
        ),
    ]
