# Generated by Django 4.1.3 on 2022-11-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movielanguages_moviedimension_moviegenre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
    ]
