# Generated by Django 4.1.3 on 2022-11-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('discount', models.CharField(blank=True, max_length=255, null=True)),
                ('validtill', models.DateTimeField(blank=True, db_column='validTill', null=True)),
            ],
            options={
                'db_table': 'Coupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Payment',
                'managed': False,
            },
        ),
    ]
