# Generated by Django 4.1.3 on 2022-11-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=20)),
                ('pincode', models.IntegerField(blank=True, db_column='Pincode', null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'City',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multiplex',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('multiplex_name', models.CharField(db_column='Multiplex_name', max_length=100)),
                ('updated_on', models.DateTimeField(blank=True, db_column='Updated_on', null=True)),
                ('created_on', models.DateTimeField(blank=True, db_column='Created_on', null=True)),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Multiplexes',
                'db_table': 'Multiplex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('hall_name', models.CharField(max_length=100)),
                ('number_of_seats', models.IntegerField(blank=True, db_column='Number_of_seats', null=True)),
                ('ishousefull', models.IntegerField(blank=True, db_column='isHouseFull', null=True)),
            ],
            options={
                'verbose_name_plural': 'Screens',
                'db_table': 'Screen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'States',
                'db_table': 'State',
                'managed': True,
            },
        ),
    ]
