# Generated by Django 4.1.3 on 2022-11-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True, 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': True, 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='multiplex',
            options={'managed': True, 'verbose_name_plural': 'Multiplexes'},
        ),
        migrations.AlterModelOptions(
            name='screen',
            options={'managed': True, 'verbose_name_plural': 'Screens'},
        ),
    ]
