# Generated by Django 4.1.3 on 2022-11-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplex', '0003_city_country_city_state_multiplex_cityid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplex',
            name='cityid',
            field=models.ForeignKey(blank=True, db_column='CityId', null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplex.city'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
