# Generated by Django 4.1.3 on 2022-11-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('numberoftickets', models.IntegerField(blank=True, db_column='NumberOfTickets', null=True)),
                ('totalcost', models.IntegerField(blank=True, db_column='TotalCost', null=True)),
            ],
            options={
                'db_table': 'Booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(blank=True, db_column='Created_on', null=True)),
                ('updated_on', models.DateTimeField(blank=True, db_column='Updated_on', null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seattype',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=25, null=True)),
                ('numofseats', models.IntegerField(blank=True, db_column='NumOfSeats', null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
            ],
            options={
                'db_table': 'SeatType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Shows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Showtiming',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, db_column='Created_on', null=True)),
                ('updated_on', models.DateTimeField(blank=True, db_column='Updated_on', null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ShowTiming',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Ticket',
                'managed': False,
            },
        ),
    ]
