# Generated by Django 4.1.3 on 2022-11-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_actor_movieactormap_reviews_and_more'),
        ('payments', '0002_alter_coupon_options'),
        ('multiplex', '0003_city_country_city_state_multiplex_cityid_and_more'),
        ('bookings', '0002_alter_booking_options_alter_seats_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paymentid',
            field=models.ForeignKey(blank=True, db_column='PaymentId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.payment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='showid',
            field=models.ForeignKey(blank=True, db_column='ShowId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.shows'),
        ),
        migrations.AddField(
            model_name='seats',
            name='screenid',
            field=models.ForeignKey(blank=True, db_column='ScreenId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='multiplex.screen'),
        ),
        migrations.AddField(
            model_name='seats',
            name='seattypeid',
            field=models.ForeignKey(blank=True, db_column='SeatTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.seattype'),
        ),
        migrations.AddField(
            model_name='shows',
            name='multiplexid',
            field=models.ForeignKey(blank=True, db_column='MultiplexId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='multiplex.multiplex'),
        ),
        migrations.AddField(
            model_name='shows',
            name='screenid',
            field=models.ForeignKey(blank=True, db_column='ScreenId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='multiplex.screen'),
        ),
        migrations.AddField(
            model_name='shows',
            name='seatid',
            field=models.ForeignKey(blank=True, db_column='SeatId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.seats'),
        ),
        migrations.AddField(
            model_name='shows',
            name='showtimeid',
            field=models.ForeignKey(blank=True, db_column='ShowTimeid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.showtiming'),
        ),
        migrations.AddField(
            model_name='showtiming',
            name='movieid',
            field=models.ForeignKey(blank=True, db_column='MovieId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movies'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bookingid',
            field=models.ForeignKey(blank=True, db_column='BookingId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='couponid',
            field=models.ForeignKey(blank=True, db_column='CouponId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.coupon'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seatid',
            field=models.ForeignKey(blank=True, db_column='SeatId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bookings.seats'),
        ),
        migrations.AlterField(
            model_name='seats',
            name='id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='seats',
            table='Seats',
        ),
    ]
