# Generated by Django 4.1.3 on 2022-11-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('updated_on', models.DateTimeField(blank=True, db_column='Updated_on', null=True)),
                ('created_on', models.DateTimeField(blank=True, db_column='Created_on', null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, db_column='Firstname', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, db_column='Lastname', max_length=50, null=True)),
                ('phonenumber', models.IntegerField(blank=True, db_column='PhoneNumber', null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=50, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
